### ISSUE TITLE
Poor performance of containers

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#93] opened 2018-10-25 08:17 UTC
Hello !
Trying to add an unordered_map to ustl I wrote a small program to check the performance of it, and also comparing ustl implementations of containers with "std".

USTL on overall has a bad performance compared to "STD" see attached sources.
[ust_performance.zip](https://github.com/msharov/ustl/files/2513923/ust_performance.zip)

The USTL Map container uses **46 times more time** than the STD for **numeric** keys.
The USTL Map container uses **81 times more time** than the STD for **string** keys.

 Here is a snippet of the output for "std::":
```
Numeric keys!
Preparing data!
Time spent = 4 ms
sizeof(key) = 8

Map numeric key!
final size = 60000
Time spent = 171 ms

Set numeric key!
final size = 60000
Time spent = 181 ms

HashMap numeric key!
final size = 60000
bucket_count = 107897
load_factor = 0.556086
Time spent = 134 ms


String keys!
Preparing data!
Time spent = 71 ms

Map string key!
mismatch found at 32321, key = 1553093940, value = 7339
mismatch found at 38672, key = 473457247, value = 32734
final size = 59998
Time spent = 299 ms

Set string key!
final size = 59998
Time spent = 308 ms

HashMap string key!
mismatch found at 32321, key = 1553093940, value = 7339
mismatch found at 38672, key = 473457247, value = 32734
final size = 59998
bucket_count = 107897
load_factor = 0.556067
Time spent = 201 ms
```
And here the output for "ustl::":
```
Numeric keys!
Preparing data!
Time spent = 5 ms
sizeof(key) = 8

Map numeric key!
final size = 60000
Time spent = 8033 ms

Set numeric key!
final size = 60000
Time spent = 3920 ms

HashMap numeric key!
final size = 60000
bucket_count = 262144
load_factor = 0.23
Time spent = 89 ms


String keys!
Preparing data!
Time spent = 135 ms

Map string key!
mismatch found at 32321, key = 1553093940, value = 7339
mismatch found at 38672, key = 473457247, value = 32734
final size = 59998
Time spent = 24444 ms

Set string key!
final size = 59998
Time spent = 18661 ms

HashMap string key!
mismatch found at 32321, key = 1553093940, value = 7339
mismatch found at 38672, key = 473457247, value = 32734
final size = 59998
bucket_count = 262144
load_factor = 0.23
Time spent = 476 ms
```

**Comment by msharov** [comment] 2018-10-25 14:10
This is a natural consequence of using vector as a map backend as a tradeoff of speed in favor of code size and simplicity. Inserting elements one-by-one will always be slower in that configuration due to having to rearrange the entire vector storage 60000 times. std::map is implemented as a linked tree, and so will always exhibit better performance in this scenario.

The example also illustrates the philosophical differences in program design between me and the academia who wrote the standard. Traditional teachings in data structures were to choose the appropriate container type for the task at hand, favoring linked containers because memory was slow and having to shuffle vector 60000 times would have been unimaginable 30 years ago. I instead always use vector for everything and design algorithms with that as a given. In your case, for instance, I would write all the map pairs into the vector first and sort the whole thing in bulk. I would also expect that reads will happen much more frequently than writes and so optimizing reads would be more important. Reads would be faster from vector because of cache locality effects and lack of memory fragmentation.

This philosophy resulted in uSTL having only vector, since I never use anything else, and is just one of the library's resulting pecularities. If you favor the academic philosophy of choosing the algorithms first and then selecting an appropriate container for it, then uSTL is simply not a good choice for you. The documentation already mentions this difference and so I'm resolving this as rejected by design.

**Closed by msharov** 2018-10-25 14:10 UTC
